[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info

[INPUT]
    Name              tail
    Path              /logs/app.log
    Parser            json
    Tag               app.logs

[OUTPUT]
    Name              es
    Match             app.logs
    Host              elasticsearch
    Port              9200
    Index             ai-assistant-backend
    Suppress_Type_Name On
